# Generated by Django 2.2.12 on 2020-04-28 17:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('owner_id', models.BigIntegerField()),
                ('shortcode', models.CharField(max_length=255, unique=True)),
                ('display_url', models.CharField(max_length=255)),
                ('published', models.IntegerField()),
                ('caption', models.TextField(null=True)),
                ('likes_count', models.IntegerField()),
                ('comments_count', models.IntegerField()),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('location', models.CharField(max_length=255, null=True)),
                ('is_video', models.BooleanField(default=False, null=True)),
                ('inst_caption', models.TextField(blank=True, null=True)),
                ('query', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
